library(dplyr)
library(lubridate)
house<- fread("household_power_consumption.txt",header = TRUE, nrows = 70000)
house$Date_and_Time<- paste(house$Date,house$Time)
house$Date_and_Time<- dmy_hms(house$Date_and_Time)
Date1<- ymd_hms("20070201 000000")
Date2<- ymd_hms("20070202 235900")
extract<- filter(house, Date_and_Time >= Date1 & Date_and_Time <= Date2)
extract$Global_active_power<- as.numeric(extract$Global_active_power)
hist(extract$Global_active_power, col = "red", xlab = "Global Active Power (kilowatts)", main = "Global Active Power")
png(filename = "plot_1.png", width = 480, height = 480,units = "px")
par(bg= "grey")
hist(extract$Global_active_power, col = "red", xlab = "Global Active Power (kilowatts)", main = "Global Active Power")
dev.copy(png, file = "plot_12.png")
dev.off()
