library(dplyr)
library(lubridate)
house<- fread("household_power_consumption.txt",header = TRUE, nrows = 70000)
house$Date_and_Time<- paste(house$Date,house$Time)
house$Date_and_Time<- dmy_hms(house$Date_and_Time)
Date1<- ymd_hms("20070201 000000")
Date2<- ymd_hms("20070202 235900")
extract<- filter(house, Date_and_Time >= Date1 & Date_and_Time <= Date2)
extract$Global_active_power<- as.numeric(extract$Global_active_power)
par(bg= "grey", mfrow = c(2,2))
with(extract,{
  plot(Date_and_Time,Global_active_power, pch = ".",xlab = "", ylab = "Global Active Power")
  lines(extract$Date_and_Time[order(extract$Date_and_Time)], extract$Global_active_power[order(extract$Date_and_Time)], xlim=range(extract$Date_and_Time), ylim=range(extract$Global_active_power), pch=16)
  plot(Date_and_Time,Voltage,pch = ".", xlab = "datetime",ylab = "Voltage")
  lines(Date_and_Time[order(Date_and_Time)], Voltage[order(Date_and_Time)], xlim=range(Date_and_Time), ylim=range(Voltage), pch=16)
  plot(extract$Date_and_Time,extract$Sub_metering_1, pch =".", xlab = "",ylab = "Energy sub metering")
  lines(Date_and_Time[order(Date_and_Time)],Sub_metering_1[order(Date_and_Time)],xlim=range(Date_and_Time), ylim=range(Sub_metering_1), pch=16)
  lines(Date_and_Time[order(Date_and_Time)],Sub_metering_2[order(Date_and_Time)],xlim=range(Date_and_Time), ylim=range(Sub_metering_2), pch=16, col = "red")
  lines(Date_and_Time[order(Date_and_Time)],Sub_metering_3[order(Date_and_Time)],xlim=range(Date_and_Time), ylim=range(Sub_metering_3), pch=16, col = "blue")
  legend("topright", lty = 1, col = c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), bty = "n", cex = .75)
  plot(Date_and_Time,Global_reactive_power, pch = ".",xlab = "datetime", ylab = "Global Reactive Power")
  lines(Date_and_Time[order(Date_and_Time)], Global_reactive_power[order(Date_and_Time)], xlim=range(Date_and_Time), ylim=range(Global_reactive_power), pch=16)
})
dev.copy(png, file = "plot_4.png")
dev.off()

